const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.NinePatch,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Plugins.gamepad,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.ScriptsInEvents["Eventos-Fase1_Event42_Act5"],
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Cnds.OnTapGestureObject
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Sólido: 0},
	{Telinha: 0},
	{PodeAtirar: 0},
	{"8Direções": 0},
	{RestritoAoLayout: 0},
	{Player: 0},
	{MovendoDireita: 0},
	{PontosInimigo1: 0},
	{Inimigo1: 0},
	{PontosInimigo2: 0},
	{Inimigo2: 0},
	{PontosInimigo3: 0},
	{Inimigo3: 0},
	{InimigoVirarEsquerda: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{Projetil: 0},
	{Teclado: 0},
	{Gamepad: 0},
	{InimigoVirarDireita: 0},
	{Score: 0},
	{PontosMesmo: 0},
	{MaiorScore: 0},
	{MaiorScoreMesmo: 0},
	{Título: 0},
	{ProjetilInimigo: 0},
	{Barreiras: 0},
	{Vida: 0},
	{FimDeJogo: 0},
	{MascaraFimdeJogo: 0},
	{Piscar: 0},
	{TítuloMenu: 0},
	{BotaoJogar: 0},
	{Toque: 0},
	{PontosOVNI: 0},
	{OVNI: 0},
	{Áudio: 0},
	{BotaoMaisSobre: 0},
	{Jogar: 0},
	{SaberMais: 0},
	{PartículasPlayer: 0},
	{PartículasInimigo1: 0},
	{PartículasInimigo2: 0},
	{PartículasInimigo3: 0},
	{História: 0},
	{BotaoVoltar: 0},
	{Voltar: 0},
	{Sprite: 0},
	{ProjetilInimigo2: 0},
	{ProjetilInimigo3: 0},
	{PartículasInimigo4: 0},
	{ProjetilInimigo4: 0},
	{Sprite2: 0},
	{Inimigo1Fase2: 0},
	{Inimgo2Fase2: 0},
	{Inimigo3Fase2: 0},
	{Fase2ProjetilInimigo1: 0},
	{ProjetilInimigo6: 0},
	{ProjetilInimigo7: 0},
	{Fase2PartículasInimigo1: 0},
	{Fase2PartículasInimigo2: 0},
	{Fase2ProjetilInimigo2: 0},
	{Fase2PartículasInimigo3: 0},
	{Fase2ProjetilInimigo3: 0},
	{Familia1: 0},
	{Familia2: 0},
	{MoverBaixo: 0},
	{InimigosMovendoDireita: 0},
	{Pontos: 0},
	{PontuaçãoMáxima: 0},
	{VidaPlayer: 0},
	{InimigosPodemMover: 0},
	{OVNIVisivel: 0},
	{JogoEstáRodando: 0},
	{NumeroLevel: 0},
	{ModificadorDeLevels: 0},
	{MoverBaixo2: 0},
	{InimigosMovendoDireita2: 0},
	{Pontos2: 0},
	{PontuaçãoMáxima2: 0},
	{VidaPlayer2: 0},
	{InimigosPodemMover2: 0},
	{OVNIVisivel2: 0},
	{JogoEstáRodando2: 0},
	{NumeroLevel2: 0},
	{ModificadorDeLevels2: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Telinha: class extends self.IWorldInstance {},
	Player: class extends self.ISpriteInstance {},
	Inimigo1: class extends self.ISpriteInstance {},
	Inimigo2: class extends self.ISpriteInstance {},
	Inimigo3: class extends self.ISpriteInstance {},
	InimigoVirarEsquerda: class extends self.ISpriteInstance {},
	Projetil: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	InimigoVirarDireita: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	PontosMesmo: class extends self.ITextInstance {},
	MaiorScore: class extends self.ITextInstance {},
	MaiorScoreMesmo: class extends self.ITextInstance {},
	Título: class extends self.ITextInstance {},
	ProjetilInimigo: class extends self.ISpriteInstance {},
	Barreiras: class extends self.ISpriteInstance {},
	Vida: class extends self.ISpriteInstance {},
	FimDeJogo: class extends self.ITextInstance {},
	MascaraFimdeJogo: class extends self.ISpriteInstance {},
	TítuloMenu: class extends self.ITextInstance {},
	BotaoJogar: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	OVNI: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	BotaoMaisSobre: class extends self.ISpriteInstance {},
	Jogar: class extends self.ITextInstance {},
	SaberMais: class extends self.ITextInstance {},
	PartículasPlayer: class extends self.IParticlesInstance {},
	PartículasInimigo1: class extends self.IParticlesInstance {},
	PartículasInimigo2: class extends self.IParticlesInstance {},
	PartículasInimigo3: class extends self.IParticlesInstance {},
	História: class extends self.ITextInstance {},
	BotaoVoltar: class extends self.ISpriteInstance {},
	Voltar: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	ProjetilInimigo2: class extends self.ISpriteInstance {},
	ProjetilInimigo3: class extends self.ISpriteInstance {},
	PartículasInimigo4: class extends self.IParticlesInstance {},
	ProjetilInimigo4: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Inimigo1Fase2: class extends self.ISpriteInstance {},
	Inimgo2Fase2: class extends self.ISpriteInstance {},
	Inimigo3Fase2: class extends self.ISpriteInstance {},
	Fase2ProjetilInimigo1: class extends self.ISpriteInstance {},
	ProjetilInimigo6: class extends self.ISpriteInstance {},
	ProjetilInimigo7: class extends self.ISpriteInstance {},
	Fase2PartículasInimigo1: class extends self.IParticlesInstance {},
	Fase2PartículasInimigo2: class extends self.IParticlesInstance {},
	Fase2ProjetilInimigo2: class extends self.ISpriteInstance {},
	Fase2PartículasInimigo3: class extends self.IParticlesInstance {},
	Fase2ProjetilInimigo3: class extends self.ISpriteInstance {},
	Familia1: class extends self.ISpriteInstance {},
	Familia2: class extends self.ISpriteInstance {}
}